plugins {
    id 'java-gradle-plugin'
    id 'groovy'
    id 'maven-publish'
}

group = 'com.tpeters'
version = '1.0.1-SNAPSHOT'
description = 'Custom Property Analyzer for Spring Boot'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}

gradlePlugin {
    plugins {
        customPropertyAnalyzer {
            id = 'com.tpeters.custom-property-analyzer'
            implementationClass = 'com.tpeters.custompropertyanalyzer.CustomPropertyAnalyzerPlugin'
        }
    }
}

repositories {
    mavenCentral()
}

dependencies {
    implementation gradleApi()
    implementation 'com.google.code.gson:gson:2.10.1'
    implementation 'org.yaml:snakeyaml:2.2'

    testImplementation 'org.junit.jupiter:junit-jupiter:5.10.2'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
    testImplementation gradleTestKit()
}

test {
    useJUnitPlatform()
}
