plugins {
    id 'java-gradle-plugin'
    id 'groovy'
    id 'maven-publish'
    id 'com.gradle.plugin-publish' version '2.1.1'
}

group = 'io.github.timoIpeters'
version = '2.0.0'
description = 'Custom Property Analyzer for Spring Boot'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}

gradlePlugin {
    website = "https://github.com/timoIpeters/spring-boot-custom-property-analyzer"
    vcsUrl = "https://github.com/timoIpeters/spring-boot-custom-property-analyzer.git"

    plugins {
        register('customPropertyAnalyzer') {
            id = 'io.github.timoIpeters.custom-property-analyzer'
            displayName = 'Custom Property Analyzer'
            description = 'Analyzes custom Spring Boot properties'
            tags.addAll('spring', 'spring-boot', 'properties')
            implementationClass = 'io.github.timoIpeters.custompropertyanalyzer.CustomPropertyAnalyzerPlugin'
        }
    }
}

repositories {
    mavenCentral()
}

dependencies {
    implementation gradleApi()
    implementation 'com.google.code.gson:gson:2.10.1'
    implementation 'org.yaml:snakeyaml:2.2'

    testImplementation 'org.junit.jupiter:junit-jupiter:5.10.2'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
    testImplementation gradleTestKit()
}

test {
    useJUnitPlatform()
}
